//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMedidorKi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDKITReto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDKITReto()
        {
            this.MEDKITCalificacion = new HashSet<MEDKITCalificacion>();
        }
    
        public int IdReto { get; set; }
        public string NombreReto { get; set; }
        public int IdCategoria { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public bool Eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDKITCalificacion> MEDKITCalificacion { get; set; }
        public virtual MEDKITCategoria MEDKITCategoria { get; set; }
    }
}
