//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMedidorKi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDKITLuchadorPersonaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDKITLuchadorPersonaje()
        {
            this.MEDKITCalificacion = new HashSet<MEDKITCalificacion>();
        }
    
        public int IdLuchadorPersonaje { get; set; }
        public int IdLuchador { get; set; }
        public int IdPersonaje { get; set; }
        public Nullable<decimal> Ki { get; set; }
        public Nullable<int> Esferas { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDKITCalificacion> MEDKITCalificacion { get; set; }
        public virtual MEDKITLuchador MEDKITLuchador { get; set; }
        public virtual MEDKITPersonaje MEDKITPersonaje { get; set; }
    }
}
