//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMedidorKi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDKITCalificacion
    {
        public int IdCalificacion { get; set; }
        public int IdLuchadorPersonaje { get; set; }
        public int IdReto { get; set; }
        public decimal Puntaje { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual MEDKITLuchadorPersonaje MEDKITLuchadorPersonaje { get; set; }
        public virtual MEDKITReto MEDKITReto { get; set; }
    }
}
