//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMedidorKi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbDesafioEntities : DbContext
    {
        public dbDesafioEntities()
            : base("name=dbDesafioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MEDKITCalificacion> MEDKITCalificacion { get; set; }
        public virtual DbSet<MEDKITCategoria> MEDKITCategoria { get; set; }
        public virtual DbSet<MEDKITLuchador> MEDKITLuchador { get; set; }
        public virtual DbSet<MEDKITLuchadorPersonaje> MEDKITLuchadorPersonaje { get; set; }
        public virtual DbSet<MEDKITPersonaje> MEDKITPersonaje { get; set; }
        public virtual DbSet<MEDKITReto> MEDKITReto { get; set; }
        public virtual DbSet<MEDKITUsuario> MEDKITUsuario { get; set; }
    }
}
